/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo5;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.testfx.api.FxRobot;
import org.testfx.api.FxToolkit;
import org.testfx.framework.junit5.ApplicationTest;
import org.testfx.framework.junit5.Start;

import static javafx.application.Application.launch;


import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assumptions.assumingThat;
import static org.testfx.assertions.api.Assertions.assertThat;
import static org.testfx.matcher.control.MenuItemMatchers.hasText;
import static org.testfx.util.DebugUtils.informedErrorMessage;


public class LauncherTest extends FxRobot {
    static Button button = new Button();

    public static class DemoApplication extends Application {

        @Override
        public void start(Stage stage) {
            assertNotNull(stage);
            button = new Button("click me!");
            button.setOnAction(actionEvent -> button.setText("clicked!"));
            stage.setScene(new Scene(new StackPane(button), 100, 100));
            stage.show();
            stage.setAlwaysOnTop(true);
        }
    }

    @BeforeEach
    void setup() throws Exception {
        ApplicationTest.launch(DemoApplication.class);
    }

    @AfterEach
    void cleanup() throws Exception {
        FxToolkit.cleanupStages();
    }

    @Test
    void should_contain_button() {
        assertThat(lookup(".button").queryButton()).hasText("click me!");
        assertThat(button).hasText("click me!");
    }

    @Test
    void should_click_on_button() {
        clickOn(".button");
        assertThat(lookup(".button").queryButton()).hasText("clicked!");
        assertThat(button).hasText("clicked!");
    }


    @Test
    void should_click_on_button(FxRobot robot) {
        robot.clickOn(".button");
    }

    }
