/*
 * This file is generated by jOOQ.
 */
package com.example.dao;


import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import com.example.database.sakila_database.model.Table.Actor;

import com.example.database.sakila_database.model.Table.Record.ActorRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import static com.example.database.sakila_database.model.Tables.ACTOR;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActorDao extends DAOImpl<ActorRecord, com.example.dao.pojos.Actor, Long> {

    public ActorDao() {
        super(Actor.ACTOR, com.example.dao.pojos.Actor.class);
    }



    public ActorDao(Configuration configuration) {
        super(Actor.ACTOR, com.example.dao.pojos.Actor.class, configuration);
    }



    public List<com.example.dao.pojos.Actor> fetchRangeOfActorId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Actor.ACTOR.ACTOR_ID, lowerInclusive, upperInclusive);
    }

    public List<com.example.dao.pojos.Actor> fetchByActorId(Long... values) {
        return fetch(Actor.ACTOR.ACTOR_ID, values);
    }

    public com.example.dao.pojos.Actor fetchOneByActorId(Long value) {
        return fetchOne(Actor.ACTOR.ACTOR_ID, value);
    }

    public Optional<com.example.dao.pojos.Actor> fetchOptionalByActorId(Long value) {
        return fetchOptional(Actor.ACTOR.ACTOR_ID, value);
    }

    public List<com.example.dao.pojos.Actor> fetchRangeOfFirstName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Actor.ACTOR.FIRST_NAME, lowerInclusive, upperInclusive);
    }

    public List<com.example.dao.pojos.Actor> fetchByFirstName(String... values) {
        return fetch(Actor.ACTOR.FIRST_NAME, values);
    }

    public List<com.example.dao.pojos.Actor> fetchRangeOfLastName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Actor.ACTOR.LAST_NAME, lowerInclusive, upperInclusive);
    }

    public List<com.example.dao.pojos.Actor> fetchByLastName(String... values) {
        return fetch(Actor.ACTOR.LAST_NAME, values);
    }


    public List<com.example.dao.pojos.Actor> fetchRangeOfLastUpdate(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Actor.ACTOR.LAST_UPDATE, lowerInclusive, upperInclusive);
    }

    public List<com.example.dao.pojos.Actor> fetchByLastUpdate(LocalDateTime... values) {
        return fetch(Actor.ACTOR.LAST_UPDATE, values);
    }

    @Override
    public Long getId(com.example.dao.pojos.Actor object) {
        return null;
    }
}
