package com.example.cs195tennis.Data.Record;

import com.example.cs195tennis.model.ServeStats;
import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;

import org.jooq.impl.TableRecordImpl;

import static com.example.cs195tennis.model.ServeStats.SERVESTATS;


/**
 * This class is generated by jOOQ.
 */


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServeStatsRecord extends TableRecordImpl<ServeStatsRecord> implements Record8<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;


    public void setServeNumber(Integer value) {
        set(0, value);
    }


    public Integer getServeNumber() {
        return (Integer) get(0);
    }

    public void setSpeed(Integer value) {
        set(1, value);
    }


    public Integer getSpeed() {
        return (Integer) get(1);
    }


    public void setPointNumber(Integer value) {
        set(2, value);
    }


    public Integer getPointNumber() {
        return (Integer) get(2);
    }


    public void setServeWidth(Integer value) {
        set(3, value);
    }


    public Integer getServeWidth() {
        return (Integer) get(3);
    }


    public void setServeDepth(Integer value) {
        set(4, value);
    }

    public Integer getServeDepth() {
        return (Integer) get(4);
    }

    public void setPlayer1Ace(Integer value) {
        set(5, value);
    }


    public Integer getPlayer1Ace() {
        return (Integer) get(5);
    }


    public void setGameId(Integer value) {
        set(6, value);
    }


    public Integer getGameId() {
        return (Integer) get(6);
    }


    public void setPlayer2Ace(Integer value) {
        set(7, value);
    }


    public Integer getPlayer2Ace() {
        return (Integer) get(7);
    }


    @Override
    public Row8<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SERVESTATS.SERVE_ID;
    }


    @Override
    public Field<Integer> field2() {return SERVESTATS.SPEED_KMH;}

    @Override
    public Field<Integer> field3() {
        return SERVESTATS.POINT_NUMBER;
    }

    @Override
    public Field<Integer> field4() {
        return SERVESTATS.SERVE_WIDTH;
    }

    @Override
    public Field<Integer> field5() {
        return SERVESTATS.SERVE_DEPTH;
    }

    @Override
    public Field<Integer> field6() {
        return SERVESTATS.PLAYER1_ACE;
    }

    @Override
    public Field<Integer> field7() {
        return SERVESTATS.GAME_ID;
    }

    @Override
    public Field<Integer> field8() {return SERVESTATS.PLAYER2_ACE;}

    @Override
    public Integer component1() {
        return getServeNumber();
    }

    @Override
    public Integer component2() {
        return getSpeed();
    }

    @Override
    public Integer component3() {
        return getPointNumber();
    }

    @Override
    public Integer component4() {
        return getServeWidth();
    }

    @Override
    public Integer component5() {return getServeDepth();}

    @Override
    public Integer component6() {
        return getPlayer1Ace();
    }

    @Override
    public Integer component7() {return getGameId();}

    @Override
    public Integer component8() {
        return getPlayer2Ace();
    }

    @Override
    public Integer value1() {
        return getServeNumber();
    }

    @Override
    public Integer value2() {
        return getSpeed();
    }

    @Override
    public Integer value3() {
        return getPointNumber();
    }

    @Override
    public Integer value4() {
        return getServeWidth();
    }

    @Override
    public Integer value5() {
        return getServeDepth();
    }

    @Override
    public Integer value6() {
        return getPlayer1Ace();
    }

    @Override
    public Integer value7() {
        return getGameId();
    }

    @Override
    public Integer value8() {
        return getPlayer2Ace();
    }

    @Override
    public ServeStatsRecord value1(Integer value) {
        setServeNumber(value);
        return this;
    }

    @Override
    public ServeStatsRecord value2(Integer value) {
        setSpeed(value);
        return this;
    }

    @Override
    public ServeStatsRecord value3(Integer value) {
        setPointNumber(value);
        return this;
    }

    @Override
    public ServeStatsRecord value4(Integer value) {
        setServeWidth(value);
        return this;
    }

    @Override
    public ServeStatsRecord value5(Integer value) {
        setServeDepth(value);
        return this;
    }

    @Override
    public ServeStatsRecord value6(Integer value) {
        setPlayer1Ace(value);
        return this;
    }

    @Override
    public ServeStatsRecord value7(Integer value) {
        setGameId(value);
        return this;
    }

    @Override
    public ServeStatsRecord value8(Integer value) {
        setPlayer2Ace(value);
        return this;
    }

    @Override
    public ServeStatsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    public ServeStatsRecord() {
        super(ServeStats.SERVESTATS);
    }


    public ServeStatsRecord(Integer fid, Integer title, Integer description, Integer category, Integer price, Integer length, Integer  gameId, Integer p1ace) {
        super(ServeStats.SERVESTATS);
        setServeNumber(fid);
        setSpeed(title);
        setPointNumber(description);
        setServeWidth(category);
        setServeDepth(price);
        setPlayer1Ace(length);
        setGameId(gameId);
        setPlayer2Ace(p1ace);
    }
}



